## Rule index for ridge regression deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run ridge regression with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule ridge_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_ridge.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_ridge_benchmark.txt"

    shell:
        "Rscript Modules/ridge/ridge_run.R {input} {output}"
