## Rule index for ridge regression deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run ridge regression with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule ridge_run:
    input:
        getC2(getC1(getBulks('{sample}'), '{sample}'),'{sample}')

    output:
        "Output/{sample}_res_ridge.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_ridge_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])
    params: 
        markers=config['markers']

    shell:
        "Rscript Modules/ridge/ridge_run.R {input} {params.markers} {output}"
