## Rule index for bseqsc deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run bseqsc with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule bseqsc_run:
    input:
        getPhenData(getC0(getBulks('{sample}'), '{sample}'), '{sample}')

    output:
        "Output/{sample}_res_bseqsc.rds"

    conda:
        "env.yaml"

    threads: config["cores"]["bseqsc"]

    benchmark:
        "Benchmarks/{sample}_bseqsc_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['bseqsc'])

    shell:
        "Rscript Modules/bseqsc/bseqsc_run.R {input} {output}"
