## Rule index for elasticNET deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run elasticNET with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule elasticNET_run:
    input:
        getC1(getBulks('{sample}'), '{sample}')

    output:
        "Output/{sample}_res_elasticNET.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_elasticNET_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])

    shell:
        "Rscript Modules/elasticNET/elasticNET_run.R {input} {output}"
