## Rule index for SCDC deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run SCDC with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule SCDC_run:
    input:
        getPhenData(getC0(getBulks()))

    output:
        "Output/{sample}_res_SCDC.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_SCDC_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['SCDC'])

    shell:
        "Rscript Modules/SCDC/SCDC_run.R {input} {output}"
