## Rule index for MuSiC deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run MuSiC with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule MuSiC_run:
    input:
        getPhenData(getC0(getBulks()))

    output:
        "Output/{sample}_res_MuSiC.rds"

    conda:
        "env.yaml"

    params:
        forceRaw = config['forceMuSiCRaw']

    benchmark:
        "Benchmarks/{sample}_MuSiC_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['MuSiC'])

    shell:
        "Rscript Modules/MuSiC/MuSiC_run.R {input} {params} {output}"
