## Rule index for FARDEEP deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run FARDEEP with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule FARDEEP_run:
    input:
         getC2(getC1(getBulks('{sample}'), '{sample}'),'{sample}')

    output:
        "Output/{sample}_res_FARDEEP.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_FARDEEP_benchmark.txt"
    
    params: 
        markers=config['markers']

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])

    shell:
        "Rscript Modules/FARDEEP/FARDEEP_run.R {input} {params.markers} {output}"
