## Rule index for FARDEEP deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run FARDEEP with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule FARDEEP_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_FARDEEP.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_FARDEEP_benchmark.txt"

    shell:
        "Rscript Modules/FARDEEP/FARDEEP_run.R {input} {output}"
