## Rule index for ComICS DCQ deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run DCQ with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule DCQ_run:
    input:
        getC2(getC1(getBulks('{sample}'), '{sample}'),'{sample}')

    output:
        "Output/{sample}_res_DCQ.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_DCQ_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])
        
    params: 
        markers=config['markers']

    shell:
        "Rscript Modules/DCQ/DCQ_run.R {input} {params.markers} {output}"
