## Rule index for EpiDISH deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run EpiDISH with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule EpiDISH_run:
    input:
        getC2(getC1(getBulks('{sample}'), '{sample}'),'{sample}')

    output:
        "Output/{sample}_res_EpiDISH.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_EpiDISH_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])
        
    params: 
        markers=config['markers']

    shell:
        "Rscript Modules/EpiDISH/EpiDISH_run.R {input} {params.markers} {output}"
