## Rule index for EpiDISH deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run EpiDISH with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule EpiDISH_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_EpiDISH.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_EpiDISH_benchmark.txt"

    shell:
        "Rscript Modules/EpiDISH/EpiDISH_run.R {input} {output}"
