## Rule index for CellMix based deconv
##
## @zgr2788
##
##
## Description:
## This file includes all the rules to run deconvolution methods in CellMix.
##
##
##      1- DSA
##      2- deconf
##      3- ssKL
##      4- ssFrobenius
##
##
##
##
##
##
##

#1- DSA
rule DSA_run:
    input:
        getC2(getBulks())

    output:
        "Output/{sample}_res_DSA.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_DSA_benchmark.txt"

    shell:
        "Rscript Modules/CellMix/DSA_run.R {input} {output}"

#2- deconf
rule deconf_run:
    input:
        getC2(getBulks())

    output:
        "Output/{sample}_res_deconf.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_deconf_benchmark.txt"

    shell:
        "Rscript Modules/CellMix/deconf_run.R {input} {output}"


#3- ssKL
rule ssKL_run:
    input:
        getC2(getBulks())

    output:
        "Output/{sample}_res_ssKL.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_ssKL_benchmark.txt"

    shell:
        "Rscript Modules/CellMix/ssKL_run.R {input} {output}"


#4- ssFrobenius
rule ssFrobenius_run:
    input:
        getC2(getBulks())

    output:
        "Output/{sample}_res_ssFrobenius.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_ssFrobenius_benchmark.txt"

    shell:
        "Rscript Modules/CellMix/ssFrobenius_run.R {input} {output}"
