## Rule index for ADAPTS deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rules to run deconvolution with ADAPTS methods using
## C1 reference.
##
##      1- proportionsInAdmixture
##      2- DCQ
##
##
##
##
##
##
##
##
##

rule proportionsInAdmixture_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_proportionsInAdmixture.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_proportionsInAdmixture_benchmark.txt"

    shell:
        "Rscript Modules/ADAPTS/proportionsInAdmixture_run.R {input} {output}"
