## Rule index for RLR deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run RLR with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule RLR_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_RLR.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_RLR_benchmark.txt"

    shell:
        "Rscript Modules/RLR/RLR_run.R {input} {output}"
