## debCAM semi-supervised clustering script with marker genes
##
## @zgr2788


suppressMessages(library(debCAM))
suppressMessages(library(BiocParallel))
suppressMessages(library(dplyr))

#Read data
args <- commandArgs(trailingOnly = TRUE)
filename_T <- args[1]
filename_C2 <- args[2]
filename_P <- args[3]

T <- readRDS(filename_T)
C2 <- readRDS(filename_C2)
P <- readRDS(filename_P)

#Switch format ta debCAM MGlist
MGlist <- C2[,c('geneName', 'cellType')] %>% split(., .[, 'cellType']) %>% lapply(., function(x) rownames(x))

#Run deconv with marker list generated by Seurat
res <- redoASest(T, MGlist, maxIter = 30) #Adjust maxIter later
res <- t(res$Aest)

#Convert P to matrix
P <- matrix(unlist(P), nrow = nrow(P), ncol = ncol(P))


#Calculate RMSE error
rmse <- sqrt(sum((P - res)^2) / length(res))

#Calculate euclidean distance (switch to any minkowski-type by adjusting p)
m_dist <- dist(rbind(as.vector(res), as.vector(unlist(P))), method = "minkowski", p = 2)

#print and exit (update later)
print(paste0("RMSE: ", rmse))
print(paste0("Euclidean Distance: ", m_dist))
