## debCAM semi-supervised clustering script with marker genes
##
## @zgr2788


suppressMessages(library(debCAM))
suppressMessages(library(dplyr))
suppressMessages(library(energy))


#Read data
args <- commandArgs(trailingOnly = TRUE)
filename_T <- args[1]
filename_P <- args[2]
filename_C2 <- args[3]
topN <- as.numeric(args[4])

T <- readRDS(filename_T)
C2 <- readRDS(filename_C2)
P <- readRDS(filename_P)

#Prefiltering for marker selection


#Switch format ta debCAM MGlist
MGlist <- C2 %>% split(., .[, 'cellType']) %>% lapply(., function(x) x[order(-abs(x$log2FC)),]) %>% lapply(., function(x) rownames(head(x,topN))) 

#Run deconv with marker list generated by Seurat
res <- redoASest(T, MGlist, maxIter = 10) #Adjust maxIter later
res <- t(res$Aest)

#Convert P to matrix
P <- matrix(unlist(P), nrow = nrow(P), ncol = ncol(P))


#Calculate RMSE error
rmse <- sqrt(mean((P - res)^2))

#Calculate euclidean distance (switch to any minkowski-type by adjusting p)
m_dist <- dist(rbind(as.vector(res), as.vector(unlist(P))), method = "minkowski", p = 2)

#Calculate Distance corr
distance_corr <- dcor(P, res)

#print and exit (update later)
print(paste0("RMSE: ", rmse))
print(paste0("Euclidean Distance: ", m_dist))
print(paste0("Distance Correlation: ", distance_corr))
