## debCAM semi-supervised deconv script with marker genes
##
## @zgr2788


suppressMessages(library(debCAM))
suppressMessages(library(dplyr))
suppressMessages(library(energy))


#Read data
args <- commandArgs(trailingOnly = TRUE)
filename_T <- args[1]
filename_P <- args[2]
filename_C2 <- args[3]
topN <- as.numeric(args[4])
filename_O <- args[5]

T <- readRDS(filename_T)
C2 <- readRDS(filename_C2)
P <- readRDS(filename_P)

#Prefiltering for marker selection


#Switch format to debCAM MGlist
MGlist <- C2 %>% split(., .[, 'cellType']) %>% lapply(., function(x) x[order(-abs(x$log2FC)),]) %>% lapply(., function(x) rownames(x))
MGlist <- MGlist[order(match(names(MGlist), rownames(P)))] #Makes sure list order is same as rownames(P) for future metrics

#Run deconv with marker list generated by Seurat
res <- redoASest(T, MGlist, maxIter = 50) #Adjust maxIter later
res <- t(res$Aest)

#Save and exit
saveRDS(res, file=filename_O)
