## Rule index for all debCAM deconvolutions
##
## @zgr2788
##
##
## Description:
## This file includes all rules associated with deconvolution using debCAM
## package. The 3 different modes are
##
##      1- Unsupervised with k coefficient
##      2- Semi-supervised with C1 reference
##      3- Semi-supervised with C2 reference
##
##
##
##
##
##
##
##

rule debCAM_unsupervised:
    input:
        getBulks()

    output:
        "Output/{sample}_debCAM_unsupervised.txt"

    params:
        cellTypes_n = config['unsupervisedParams']['expectedTypes']

    conda:
        "env.yaml"

    threads: 30

    shell:
        """
        Rscript Modules/debCAM/debCAM_u.R {input} {params}
        touch {output}
        """



rule debCAM_marker:
    input:
        getC2(getBulks())

    output:
        "Output/{sample}_debCAM_marker.txt"

    conda:
        "env.yaml"

    params:
        topN = config['markerParams']['topN']

    shell:
        """
        Rscript Modules/debCAM/debCAM_marker.R {input} {params}
        touch {output}
        """



rule debCAM_C1:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_debCAM_C1.txt"

    conda:
        "env.yaml"

    shell:
        """
        Rscript Modules/debCAM/debCAM_C1.R {input}
        touch {output}
        """
