## C & T tables scaling/transformation script for use in deconvolution methods
##
## @zgr2788
##
## Description:
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##

rule scaleTransform:
    input:
        C_table = 'Input/References/{sample}_C0.rds',
        T_table = 'Input/Psuedobulks/{sample}_pbulks.rds'

    output:
        'Input/Normalized_tables/{sample}_pbulks_scaled_transformed.rds',
        'Input/Normalized_tables/{sample}_C0_scaled_transformed.rds'

    conda:
        'env.yaml'

    params:
        scaleTMethod = config['stParam']['scaleT'],
        scaleCMethod = config['stParam']['scaleC'],
        transMethod = config['stParam']['transform']

    shell:
        """
    Rscript Modules/Scale_transform/scaleTable_T.R {input.T_table} {params.scaleTMethod}
    Rscript Modules/Scale_transform/scaleTable_C.R {input.C_table} {params.scaleCMethod}
    Rscript Modules/Scale_transform/transformTables.R Input/Normalized_tables/{wildcards.sample}_pbulks_scaled.rds Input/Normalized_tables/{wildcards.sample}_C0_scaled.rds {params.transMethod}
        """
