## Rule index for lasso regression deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run lasso regression with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule lasso_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_lasso.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_lasso_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])

    shell:
        "Rscript Modules/lasso/lasso_run.R {input} {output}"
