## Rule index for CIBERSORT deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run CIBERSORT with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule CIBERSORT_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_CIBERSORT.rds"

    conda:
        "env.yaml"

    threads: config["cores"]["CIBERSORT"]

    benchmark:
        "Benchmarks/{sample}_CIBERSORT_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])

    shell:
        "Rscript Modules/CIBERSORT/CIBERSORT_run.R {input} {output}"
