## Rule index for DeconRNASeq deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run DeconRNASeq with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule DeconRNASeq_run:
    input:
        getC1(getBulks())

    output:
        "Output/{sample}_res_DeconRNASeq.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_DeconRNASeq_benchmark.txt"

    shell:
        "Rscript Modules/DeconRNASeq/DeconRNASeq_run.R {input} {output}"
