## Rule index for DeconRNASeq deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run DeconRNASeq with C1 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule DeconRNASeq_run:
    input:
        getC2(getC1(getBulks('{sample}'), '{sample}'),'{sample}')

    output:
        "Output/{sample}_res_DeconRNASeq.rds"

    conda:
        "env.yaml"

    benchmark:
        "Benchmarks/{sample}_DeconRNASeq_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['minorOps'])
    
    params: 
        markers=config['markers']

    shell:
        "Rscript Modules/DeconRNASeq/DeconRNASeq_run.R {input} {params.markers} {output}"
