## Conversion module for the deconvolution benchmarking pipeline
##
## @zgr2788
##
##
## Description:
##
##  Converts input .h5ad file to a Seurat object and saves the object as a
## .rds file to be loaded back for the future steps of the pipeline
##
## TODO:
##  - After I/O is sorted out, need to decide on where to put files and
## adjust the script.
##
##  - Check accuracy of generation through sceasy, if not accurate switch
## main to seuratdisk, which is more problematic.
##
##
##
##

#Rule for converting anndata to seurat object
rule convertAnndata:
    input:
        "Input/{sample}.h5ad"

    output:
        "Scratch/Convert_split/{sample}.rds"

    conda:
        "env.yaml"

    shell:
        "Rscript Modules/Convert_split/convert.R Input/{wildcards.sample}.h5ad"



#Rule for splitting seurat object to be sent to different workflows
rule splitCells:
    input:
        "Scratch/Convert_split/{sample}.rds"

    output:
        "Output/Cell_splits/{sample}_gen.rds",
        "Output/Cell_splits/{sample}_C0.rds"

    conda:
        "env.yaml"

    shell:
        "Rscript Modules/Convert_split/split.R Scratch/Convert_split/{wildcards.sample}.rds"
