## Rule index for DWLS deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run DWLS with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule DWLS_run:
    input:
        getPhenData(getC0(getBulks()))

    output:
        "Output/{sample}_res_DWLS.rds"

    conda:
        "env.yaml"

    threads: 16

    benchmark:
        "Benchmarks/{sample}_DWLS_benchmark.txt"

    shell:
        "Rscript Modules/DWLS/DWLS_run.R {input} {threads} {output}"
