## Rule index for DWLS deconv
##
## @zgr2788
##
##
## Description:
## This file includes the rule to run DWLS with C0 reference.
##
##
##
##
##
##
##
##
##
##
##
##
##

rule DWLS_run:
    input:
        getPhenData(getC0(getBulks('{sample}'), '{sample}'), '{sample}')

    output:
        "Output/{sample}_res_DWLS.rds"

    conda:
        "env.yaml"

    threads: config["cores"]["DWLS"]

    benchmark:
        "Benchmarks/{sample}_DWLS_benchmark.txt"

    resources:
        mem_mb=getMB(config['mem_gb']['DWLS'])

    shell:
        """
        mkdir -p {wildcards.sample}_scratch
        Rscript Modules/DWLS/DWLS_run.R {input} {threads} {output} {wildcards.sample}_scratch
        """
